repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0  # Версія isort
#    hooks:
#      - id: isort
#        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v4.0.1  # Версія flake8
#    hooks:
#      - id: flake8
#        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
